### ISSUE TITLE
你好我照着readme做，但是没有渲染出界面，请问是还缺少什么依赖吗

### ISSUE THREAD

**Issue by wraptor** [xinlei3166/vuepress-plugin-demoblock-plus#1]
![image](https://user-images.githubusercontent.com/52092701/137662780-65524208-315b-40c9-9dba-8e322c391180.png)
![image](https://user-images.githubusercontent.com/52092701/137662730-6112302c-a040-4914-917b-49cc5102b471.png)
![image](https://user-images.githubusercontent.com/52092701/137662751-0504b394-7a39-4eea-819d-f0052d64193b.png)

**Comment by xinlei3166** [comment]
@wraptor 代码需要用对应的语言包裹。
:::demo 使用`size`、`style`属性来定义 Card 的样式。

```vue
<template>
  <div class="card-wrap">
    <div class="card">{{ title }}</div>
  </div>
</template>
```

:::
