### ISSUE TITLE
"vuepress": "^2.0.0-beta.43",使用1.5.1 版本不生效

### ISSUE THREAD

**Issue by NewCoder798** [xinlei3166/vuepress-plugin-demoblock-plus#10]
"vuepress": "^2.0.0-beta.43",
 使用vuepress-plugin-demoblock-plus的1.5.1 版本不生效，如下图

使用最新版的1.6.0也不生效，求作者帮解答，

**Comment by xinlei3166** [comment]
提供个 github demo 地址，看下。

**Comment by NewCoder798** [comment]
> 提供个 github demo 地址，看下。

https://gitee.com/NewCoderMCL/vuepress-ui
请大佬帮看下

**Comment by xinlei3166** [comment]
> > 提供个 github demo 地址，看下。
> 
> https://gitee.com/NewCoderMCL/vuepress-ui 请大佬帮看下

仓库没权限

**Comment by NewCoder798** [comment]
> > > 提供个 github demo 地址，看下。
> > 
> > 
> > https://gitee.com/NewCoderMCL/vuepress-ui 请大佬帮看下
> 
> 仓库没权限

我申请了开源但是需要2个工作日审核，要不您先加我vx：macuiling1995

**Comment by NewCoder798** [comment]
> > > 提供个 github demo 地址，看下。
> > 
> > 
> > https://gitee.com/NewCoderMCL/vuepress-ui 请大佬帮看下
> 
> 仓库没权限

开源通过了，请帮忙看下吧，感激不尽

**Comment by xinlei3166** [comment]
> 

安装1.6.0版本，使用require方法使用插件就行。
```
const demoblockPlugin = require('vuepress-plugin-demoblock-plus')
  plugins: [
    demoblockPlugin({
      customClass: 'demoblock-custom',
      // theme: 'github-light',
      cssPreprocessor: 'less',
      scriptReplaces: [
        { searchValue: /const ({ defineComponent as _defineComponent }) = Vue/g,
          replaceValue: 'const { defineComponent: _defineComponent } = Vue'
        }
      ]
    })
]
```

版本号： 
```
    "@vuepress/plugin-shiki": "^2.0.0-beta.46",
    "vuepress-plugin-demoblock-plus": "^1.6.0",
    "vuepress-vite": "^2.0.0-beta.46"
```

我本地测试没问题，运行正常。
