### ISSUE TITLE
vuepress-webpack@2.0.0-beta.49版本下示例没有渲染

### ISSUE THREAD

**Issue by wjx19931104** [xinlei3166/vuepress-plugin-demoblock-plus#11]
vuepress-webpack@2.0.0-beta.48版本正常
![image](https://user-images.githubusercontent.com/8566226/178669064-08e3d2bd-4bf9-4ca8-b55b-2159444fa3b1.png)
控制台无报错等信息

**Comment by cgx452306705** [comment]
我也遇到这个问题了

**Comment by wuyifan0203** [comment]
俺也一样
<img width="1535" alt="image" src="https://user-images.githubusercontent.com/58818101/181205270-951bd157-9f6e-426d-8404-8ba54c4a5301.png">

**Comment by saonan90077** [comment]
俺也一样

**Comment by xinlei3166** [comment]
v2正在使用TypeScript重新开发中，支持最新版，近期发布。

**Comment by xinlei3166** [comment]
v2版本已发布
