### ISSUE TITLE
Theming for code preview

### ISSUE THREAD

**Issue by tomatopickle** [xinlei3166/vuepress-plugin-demoblock-plus#3]
First of all, amazing work. Yours is the only plugin to support Vuepress 2. I have been using you're pluging. But I realized that I can't change the theme for the code. I realized you were using Shiki and it supports multiple themes. So can you please add a theming feature?

Thanks

**Comment by tomatopickle** [comment]
Btw, if you find it difficult to make a custom theme option, just make Shiki's [css variables theme](https://github.com/shikijs/shiki/blob/main/docs/themes.md#theming-with-css-variables) so that we can customize the code ourselves

**Comment by xinlei3166** [comment]
@tomatopickle Version 1.5.0 already supports Vuepress darkMode and ShiKi css-variables.

**Comment by tomatopickle** [comment]
Yup, it's fixed. Thanks a lot!
