### ISSUE TITLE
vue组件里对象的逗号被隐藏了

### ISSUE THREAD

**Issue by Xyuan-abs** [xinlei3166/vuepress-plugin-demoblock-plus#4]
![image](https://user-images.githubusercontent.com/64180387/145973075-e7235141-6df7-4d9c-9274-3fdf5e9bd442.png)
对象的逗号被设置为透明的了  这个是需要哪里配置吗

**Comment by xinlei3166** [comment]
> ![image](https://user-images.githubusercontent.com/64180387/145973075-e7235141-6df7-4d9c-9274-3fdf5e9bd442.png) 对象的逗号被设置为透明的了 这个是需要哪里配置吗

@Xyuan-abs version 1.5.1 已修复此问题。
